### ISSUE TITLE
Question: state of the project.

### ISSUE THREAD

**Issue by kalombos** [kbbdy/zipstream#2] opened 2020-06-22 07:22 UTC
Hi, your project looks nice and i could not find better one for python. Thank you, you save me a lot of time. But it looks abandoned and i am worried if it is stable for the production? Also i could not find the package on the pypi so i had to upload it [there](https://pypi.org/project/aiozipstream/) so i was able to add the dependency to the requirements.txt Do you have any plans for the project?

**Comment by kbbdy** [comment] 2020-08-06 09:27
Hi. It's not abandoned, but i can't find some time to make it work better. Currently i plan to make some fixes to project. I'm happy that You uploaded it to pypi. Lack of progress on project is caused by switching to node in new projects. I promise to fix bug and bump version to 0.5 in week or two, and then It will be quite to work on production.

Current status is: it works, but I need to fix small bug causing that zip files are problematic on OS-X. 
I tested my zip files with many zip applications and it works except iOS. This is caused by bug reported to me by arthanson, and there is also fix for that.

**Comment by kalombos** [comment] 2020-08-06 09:51
I can add you as an owner on pypi for the package just need your login.

**Comment by kingmad** [comment] 2020-09-07 09:15
we're considering to use this package during one of our project new feature's implementation and wondering when the version 0.5 will be released? @kbbdy are you able to give any ETA?
It'd would be great to build new solution based on prod-ready version :)

**Comment by kbbdy** [comment] 2020-09-23 12:30
Hi. I just fixed some issues in zipstream and in tests. I also made sure that the library works with the latest python versions (3.9). Version is bumped to 0.5.

**Comment by kbbdy** [comment] 2020-09-23 12:33
The proposition of renaming zipstream aiozipstream is fine, because nobody currently uses sync version of python on backend. I think that aiozipstream should be separated library under new name, and zipstream should stay as is, to avoid breaking old code for people using current synchronous lib.

**Closed by kbbdy** 2020-09-23 12:33 UTC
